Controllers/Expense/ExpenseController.cs
using System.Text.Json;
using Microsoft.AspNetCore.Mvc;
using N3C_348209_parodi_client.Models.Dtos.Log;
using N3C_348209_parodi_client.ServicesInterfaces;
using RestSharp;

namespace N3C_348209_parodi_client.Controllers.Expense
{
    public class ExpenseController : Controller
    {
        private string _url = "https://mauricioapi-eddggufkfza4a3gv.brazilsouth-01.azurewebsites.net";
        private readonly ISelectionServices _selectionServices;

        public ExpenseController(ISelectionServices selectionServices)
        {
            _selectionServices = selectionServices;
        }
        public IActionResult Logs()
        {
            ViewBag.Expenses = _selectionServices.GetExpensesForSelect();
            return View();
        }
        [HttpPost]
        public IActionResult Logs(int expenseId)
        {
            var client = new RestClient(_url);
            var request = new RestRequest($"/api/v1/Expenses/{expenseId}/logs", Method.Get);

            request.AddHeader("Authorization", $"Bearer {HttpContext.Session.GetString("token")}");

            var response = client.Execute(request);

            if ((int)response.StatusCode == 200)
            {
                var logs = JsonSerializer.Deserialize<IEnumerable<LogDto>>(
                    response.Content!,
                    new JsonSerializerOptions { PropertyNameCaseInsensitive = true });

                if (!logs.Any())
                {
                    ViewBag.Error = "Este gasto no tiene logs registrados.";
                    ViewBag.Expenses = _selectionServices.GetExpensesForSelect();
                    return View(new List<LogDto>());
                }

                ViewBag.Expenses = _selectionServices.GetExpensesForSelect();
                return View(logs);
            }

            ViewBag.Error = "No se encontraron logs.";
            ViewBag.Expenses = _selectionServices.GetExpensesForSelect();
            return View(new List<LogDto>());
        }

    }
}

Controllers/Payment/PaymentController.cs
using System.Runtime.CompilerServices;
using System.Text.Json;
using LibreriaLogicaAplicacion.Dtos.Expense;
using LibreriaLogicaAplicacion.Dtos.Payment;
using LibreriaLogicaAplicacion.Dtos.User;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using N3C_348209_parodi_client.Models.Dtos.Payment;
using RestSharp;

namespace N3C_348209_parodi_client.Controllers.Payment
{
    public class PaymentController : Controller
    {
        private string _url = "https://mauricioapi-eddggufkfza4a3gv.brazilsouth-01.azurewebsites.net";

        [HttpGet]
        public IActionResult Create()
        {
            var expenses = GetExpensesForSelect();
            var users = GetUsersForSelect();
            ViewBag.Expenses = expenses;
            ViewBag.Users = users;
            return View();
        }

        [HttpPost]
        public IActionResult Create(AddPaymentDto dto)
        {
            var client = new RestClient(_url);
            var request = new RestRequest("/api/v1/Payments", Method.Post);

            request.AddHeader("Content-Type", "application/json");
            request.AddHeader("Authorization", $"Bearer {HttpContext.Session.GetString("token")}");

            request.AddJsonBody(dto);

            RestResponse response = client.Execute(request);

            if ((int)response.StatusCode == 400)
            {
                ViewBag.Message = "Por favor verifique los campos ingresados";
            }
            else if ((int)response.StatusCode == 500)
            {
                ViewBag.Message = "Un error inesperado ha ocurrido";
            }
            else if ((int)response.StatusCode == 201)
            {
                ViewBag.CreatedMessage = "Pago creado correctamente";
            }
            else
            {
                ViewBag.Message = $"Error inesperado: {response.StatusCode}";
            }

            var expenses = GetExpensesForSelect();
            var users = GetUsersForSelect();
            ViewBag.Expenses = expenses;
            ViewBag.Users = users;

            return View(dto);
        }

        [HttpGet]
        public IActionResult UserPayments()
        {
            var client = new RestClient(_url);
            var request = new RestRequest("/api/v1/Users/payments", Method.Get);

            request.AddHeader("Authorization", $"Bearer {HttpContext.Session.GetString("token")}");

            RestResponse response = client.Execute(request);

            if ((int)response.StatusCode == 200)
            {
                var payments = JsonSerializer.Deserialize<IEnumerable<GetAllPaymentsDto>>(
                    response.Content!,
                    new JsonSerializerOptions { PropertyNameCaseInsensitive = true }
                );

                return View(payments);
            }

            ViewBag.Error = "No hay pagos para este usuario";
            return View(new List<GetAllPaymentsDto>());
        }


        public IEnumerable<ExpenseDto> GetExpensesForSelect()
        {
            string endpointUrl = "/api/v1/Expenses";
            var client = new RestClient(_url);
            var request = new RestRequest(endpointUrl, Method.Get);

            request.AddHeader("Content-Type", "application/json");
            request.AddHeader("Authorization", $"Bearer {HttpContext.Session.GetString("token")}");

            RestResponse response = client.Execute(request);

            if ((int)response.StatusCode == 200)
            {
                var expenses = JsonSerializer.Deserialize<IEnumerable<ExpenseDto>>(
                    response.Content!,
                    new JsonSerializerOptions { PropertyNameCaseInsensitive = true }
                );
                return expenses;
            }

            return new List<ExpenseDto>();
        }

        private IEnumerable<UserSelectDto> GetUsersForSelect()
        {
            string endpointUrl = "/api/v1/Users/getAll";
            var client = new RestClient(_url);
            var request = new RestRequest(endpointUrl, Method.Get);

            request.AddHeader("Content-Type", "application/json");
            request.AddHeader("Authorization", $"Bearer {HttpContext.Session.GetString("token")}");

            RestResponse response = client.Execute(request);

            if ((int)response.StatusCode == 200)
            {
                var users = JsonSerializer.Deserialize<IEnumerable<UserSelectDto>>(
                    response.Content!,
                    new JsonSerializerOptions { PropertyNameCaseInsensitive = true }
                );
                return users;
            }

            return new List<UserSelectDto>();
        }
    }
}

Controllers/Team/TeamController.cs
using Microsoft.AspNetCore.Mvc;
using N3C_348209_parodi_client.Models.Dtos.Team;
using RestSharp;

namespace N3C_348209_parodi_client.Controllers.Team
{
    public class TeamController : Controller
    {
        private string _url = "https://mauricioapi-eddggufkfza4a3gv.brazilsouth-01.azurewebsites.net";
        [HttpGet]
        public IActionResult GetTeamsByPayments()
        {
            return View();
        }
        [HttpGet]
        public IActionResult GetTeams(double amount)
        {
            var client = new RestClient(_url);
            var request = new RestRequest($"/api/v1/Teams/TeamsByAmount?amount={amount}", Method.Get);

            request.AddHeader("Authorization", $"Bearer {HttpContext.Session.GetString("token")}");

            var response = client.Execute<IEnumerable<TeamDto>>(request);

            if ((int)response.StatusCode != 200)
            {
                ViewBag.Message = "No se encontraron equipos con ese monto.";
                return View("GetTeamsByPayments", Enumerable.Empty<TeamDto>());
            }

            return View("GetTeamsByPayments", response.Data);
        }
    }
}

Controllers/User/UserController.cs
using System.Net;
using System.Text.Json;
using Microsoft.AspNetCore.Mvc;
using N3C_348209_parodi_client.Models.Dtos.User;
using RestSharp;

namespace N3C_348209_parodi_client.Controllers.User
{
    public class UserController : Controller
    {
        private string _url = "https://mauricioapi-eddggufkfza4a3gv.brazilsouth-01.azurewebsites.net";

        [HttpGet]
        public IActionResult ResetPassword()
        {
            return View(new UserIndexDto());
        }

        [HttpPost]
        public IActionResult ResetPassword(UserIndexDto dto)
        {
            var endpoint = "/api/v1/Users/reset";

            var client = new RestClient(_url);
            var request = new RestRequest(endpoint, Method.Put);

            request.AddHeader("Content-Type", "application/json");

            request.AddHeader("Authorization", $"Bearer {HttpContext.Session.GetString("token")}");

            request.AddJsonBody(dto);

            var response = client.Execute(request);

            if (response.StatusCode == HttpStatusCode.OK)
            {
                var result = JsonSerializer.Deserialize<UserPasswordResetResponse>(
                    response.Content!,
                    new JsonSerializerOptions { PropertyNameCaseInsensitive = true }
                );

                ViewBag.NewPassword = result.newPassword;
                return View(dto);
            }
            else if (response.StatusCode == HttpStatusCode.NotFound)
            {
                ViewBag.Error = "El usuario no existe.";
            }
            else
            {
                ViewBag.Error = "Error desconocido al resetear la contraseña.";
            }

            return View(dto);
        }

    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - N3C_348209_parodi_client</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/N3C_348209_parodi_client.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        @{
            var role = Context.Session.GetString("role");
            var isLogged = !string.IsNullOrEmpty(role);
        }

        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">

                        <!-- Botón visible solo si NO está logueado -->
                        @if (!isLogged)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Home" asp-action="Login">Iniciar sesión</a>
                            </li>
                        }

                        <!-- Botones visibles si está logueado (cualquier rol) -->
                        @if (isLogged)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Home" asp-action="Logout">Cerrar sesión</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Payment" asp-action="Create">Crear un pago</a>
                            </li>

                        }
                        <!-- RF2 — Solo Gerentes -->
                        @if (role == "Manager")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Team" asp-action="GetTeamsByPayments">Buscar equipos</a>
                            </li>
                        }

                <!-- RF2 — Solo Empleados y Gerentes -->
                        @if (role == "Employee" || role == "Manager")
                        {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Payment" asp-action="UserPayments">Mis pagos</a>
                        </li>
                        }

                <!-- Solo Administradores -->
                        @if (role == "Administrator")
                        {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="User" asp-action="ResetPassword">Resetear contraseña usuario</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Expense" asp-action="Logs">
                                Auditoría de gastos
                            </a>
                        </li>
                        }

            </ul>
        </div>
    </div>
</nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - N3C_348209_parodi_client - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>